version: "3.3"

services:
  apt-decor-next:
    container_name: apt-decor-next
    restart: always
    image: node:20.10.0
    ports:
      - "4000:3000"
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/apt-decor-next
    working_dir: /usr/src/apt-decor-next

    networks:
      - client_network

      # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client_network:
    driver: bridge
# apt-decor-next: localhost:4000 <=> container:3000
# apt-decor-api: localhost:4000 <=> container:3007
# apt-decor-batch: localhost:4000 <=> container:3008
